name: MagicBroom
version: ${project.version}
api-version: 1.17
main: xyz.dwaslashe.core.Main
depend:
  - ForceResourcepacks
  - Vault
loadbefore:
  - VehiclesPlusPro
authors:
  - WuShei
  - DwaSlashe
